const { Schema, model } = require("mongoose");
const Limites = Schema({
guildID: {type: String, default: ''},
userID: {type: String, default: ''},
channelCreate: {type: Number, default: 0},
channelDelete: {type: Number, default: 0},
channelUpdate: {type: Number, default: 0},
roleCreate: {type: Number, default: 0},
roleDelete: {type: Number, default: 0},
roleUpdate: {type: Number, default: 0},
emojiCreate: {type: Number, default: 0},
emojiDelete: {type: Number, default: 0},
emojiUpdate: {type: Number, default: 0},
stickerCreate: {type: Number, default: 0},
stickerDelete: {type: Number, default: 0},
stickerUpdate: {type: Number, default: 0},
banCreate: {type: Number, default: 0},
kickCreate: {type: Number, default: 0},
memberRoleUpdate: {type: Number, default: 0},
channelCreateLimit: {type: Number, default: 2},
channelDeleteLimit: {type: Number, default: 1},
channelUpdateLimit: {type: Number, default: 2},
roleCreateLimit: {type: Number, default: 2},
roleDeleteLimit: {type: Number, default: 1},
roleUpdateLimit: {type: Number, default: 2},
emojiCreateLimit: {type: Number, default: 2},
emojiDeleteLimit: {type: Number, default: 1},
emojiUpdateLimit: {type: Number, default: 2},
stickerCreateLimit: {type: Number, default: 2},
stickerDeleteLimit: {type: Number, default: 1},
stickerUpdateLimit: {type: Number, default: 2},
banCreateLimit: {type: Number, default: 1},
kickCreateLimit: {type: Number, default: 1},
memberRoleUpdateLimit: {type: Number, default: 1},
});

module.exports = model("Limites", Limites);